
project_id = "vmwiigfhjvwecnlwppnj"

[functions.twilio-token]
verify_jwt = true

[functions.voice-call]
verify_jwt = true

[functions.voice-webhook]
verify_jwt = false

[functions.call-status]
verify_jwt = false
