// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmwiigfhjvwecnlwppnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtd2lpZ2ZoanZ3ZWNubHdwcG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDE1NzEsImV4cCI6MjA2MDUxNzU3MX0.bHAZN8-ToQfcxPfhHgLQbUnXXwBkpmachGanLaZpwPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);